# Generated by Django 3.1.2 on 2021-01-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_id',
        ),
    ]
