# Generated by Django 3.1.2 on 2021-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20210301_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
