# Generated by Django 3.1.2 on 2021-02-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestEmail',
        ),
    ]
