# Generated by Django 3.1.2 on 2021-01-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillingProfile', '0002_auto_20201223_0202'),
        ('Order', '0004_auto_20201220_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillingProfile.billingprofile'),
        ),
    ]
