# Generated by Django 3.1.2 on 2020-12-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillingProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
