# Generated by Django 3.1.2 on 2021-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
