# Generated by Django 3.1.2 on 2021-03-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20210311_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
